djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('polls/', include('polls.urls'))
]

djangoProject/polls/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path(' ', views.index, name= 'index'),
    path('<int:question_id>/', detail, name='detail'),
    path('<int:question_id>/results/', results, name='results'),
    path('<int:question_id>/vote/', vote, name='vote'),
]

djangoProject/polls/models.py
from django.utils import timezone
from django.db import models
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=250)
    pub_date = models.DateTimeField()

    def __str__(self):
        return f'{self.question_text}'

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=1))


class Choice(models.Model):
    choice_text = models.CharField(max_length=250)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.choice_text}'

djangoProject/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

djangoProject/templates/detail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
</head>
<body>
    <form action="{% url 'vote' question.id %}" method="post">
        {% csrf_token %}

        <h1>{{ question.question_text }}</h1>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        {% for choice in question.choice_set.all %}
            <input type="radio" name="my_selection" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}

        <input type="submit" value="Vote">
    </form>
</body>
</html>

djangoProject/templates/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    {% if question_list %}
        <ul>
            {% for question in question_list %}
                <li>
                    <h2>
                    <!-- <a href="/polls/{{question.id}}">{{question.question_text}}</a> -->
                    <a href="{% url 'detail' question.id %}">{{question.question_text}}</a>
                    </h2>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available as of now, maybe you can check again later.</p>
    {% endif %}
</body>
</html>

djangoProject/templates/result.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
</head>
<body>
    <h1> {{question.question_text}} </h1>

    <h3>
        <ul>
            {% for choice in question.choice_set.all %}
                <li>
                    {{choice.choice_text}} - {{ choice.votes }} votes
                </li>
            {% endfor %}
        </ul>
    </h3>

    <a href="{% url 'detail' question.id %}">Vote again?</a>
</body>
</html>